//
//  ProductDetailRouter.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 17.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductDetailRoutingLogic
{
    func viewDismiss()
    func navigateToBaskets()
}

protocol ProductDetailDataPassing
{
  var dataStore: ProductDetailDataStore? { get }
}

class ProductDetailRouter: NSObject, ProductDetailRoutingLogic, ProductDetailDataPassing
{
  weak var viewController: ProductDetailViewController?
  var dataStore: ProductDetailDataStore?


  // MARK: Navigation

    func viewDismiss() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    func navigateToBaskets() {
        let vc  = BasketsViewController()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
