//
//  ProductDetailPresenter.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 17.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductDetailPresentationLogic
{
  func presentSomething(response: ProductDetail.Something.Response)
    func displayProductDetail(viewModel: ProductList.ProductModel)
    func viewDismiss()
    func productAddedToBasket()
    func setBasketButtonBadge()
}

class ProductDetailPresenter: ProductDetailPresentationLogic
{
  weak var viewController: ProductDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProductDetail.Something.Response)
  {
    
  }
    func displayProductDetail(viewModel: ProductList.ProductModel) {
        viewController?.displayProductDetail(viewModel: viewModel)
    }
    func viewDismiss() {
        viewController?.viewDismiss()
    }
   func productAddedToBasket() {
       viewController?.notifyBasketProductCount()
    }
    func setBasketButtonBadge() {
        viewController?.setBasketButtonBadge()
    }
}
