//
//  ProductDetailWorker.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 17.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseDatabase

class ProductDetailWorker
{
    let ref = Database.database().reference().child("baskets")
    func addBasket(product: ProductList.ProductModel?, piece: Int?, completion: @escaping ((_ isAdded: Bool?)-> ())) {

        var model = product
        model?.count = piece
        do {
            let encoder = JSONEncoder()
            let data = try encoder.encode(model)
            let json = try JSONSerialization.jsonObject(with: data)
            ref.childByAutoId()
                .setValue(json)
            completion(true)
        } catch {
            print("an error occurred", error)
        }
        
    }
}
