//
//  ProductListPresenter.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 17.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductListPresentationLogic
{
    func presentProductList(viewModel: [ProductList.ProductModel]?)
    func navigateToProductDetail(product: ProductList.ProductModel)
    func updateNavbarBaskets()
    func productAddedToBasket()
    func setBasketButtonBadge()
}

class ProductListPresenter: ProductListPresentationLogic
{
    weak var viewController: ProductListDisplayLogic?
    
    func presentProductList(viewModel: [ProductList.ProductModel]?) {
        viewController?.presentProductList(viewModel: viewModel)
    }
    func navigateToProductDetail(product: ProductList.ProductModel) {
        viewController?.navigateToProductDetail(product: product)
    }
    func updateNavbarBaskets() {
        viewController?.updateNavbarBaskets()
    }
    func productAddedToBasket() {
        viewController?.notifyBasketProductCount()
    }
    func setBasketButtonBadge() {
        viewController?.setBasketButtonBadge()
    }
}
