//
//  ProductListRouter.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 17.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ProductListRoutingLogic
{
    func navigateToProductDetail()
    func navigateToBaskets()
}

protocol ProductListDataPassing
{
    var dataStore: ProductListDataStore? { get }
    var product:  ProductList.ProductModel? { get set }
    
}

class ProductListRouter: NSObject, ProductListRoutingLogic, ProductListDataPassing
{
    var product: ProductList.ProductModel?
    weak var viewController: ProductListViewController?
    var dataStore: ProductListDataStore?
    
    // MARK: Navigation
    
    func navigateToProductDetail() {
        let vc  = ProductDetailViewController()
        vc.interactor?.viewModel = self.product
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    func navigateToBaskets() {
        let vc  = BasketsViewController()
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
