//
//  BasketsPresenter.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 18.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasketsPresentationLogic
{
    func basketFetched(viewModel: [ProductList.ProductModel]?)
    func reloadData()
}

class BasketsPresenter: BasketsPresentationLogic
{
  weak var viewController: BasketsDisplayLogic?
  
  // MARK: Do something
    
    func basketFetched(viewModel: [ProductList.ProductModel]?) {
        viewController?.presentBasketList(viewModel: viewModel)
    }
    func reloadData() {
        viewController?.reloadData()
    }
}
