//
//  BasketsInteractor.swift
//  eCommerceVIP
//
//  Created by enes.sakut on 18.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BasketsBusinessLogic
{
    func fetchBaskets()
    func heightForRowAt() -> CGFloat
    func productForIndexPath(_ indexPath: IndexPath) -> ProductList.ProductModel?
    var products: [ProductList.ProductModel]? { get set }
    var numberOfRowsInSection: Int { get set }
    func deleteBaskets()
}

protocol BasketsDataStore
{
  //var name: String { get set }
}

class BasketsInteractor: BasketsBusinessLogic, BasketsDataStore
{
  var presenter: BasketsPresentationLogic?
  var worker: BasketsWorker?
    var numberOfRowsInSection: Int = 0
    var products: [ProductList.ProductModel]? {
        didSet {
            numberOfRowsInSection = products?.count ?? .zero
        }
    }
  
  // MARK: Do something
    func fetchBaskets() {
        worker = BasketsWorker()
        let _ = worker?.fetchBaskets(completion: { [self] productModel in
            presenter?.basketFetched(viewModel: productModel)
        })
    }
    func heightForRowAt() -> CGFloat {
        return 150
    }
    func productForIndexPath(_ indexPath: IndexPath) -> ProductList.ProductModel? {
        products?[indexPath.row]
    }
    func deleteBaskets() {
        worker = BasketsWorker()
        let _ = worker?.deleteBaskets(completion: { [self] productModel in
            presenter?.reloadData()
        })
    }
}
